name: Flutter CI/CD Release

on:
  push:
    tags:
      - "v*" # Runs when pushing a tag like v1.0.0

jobs:
  build:
    name: Build Flutter APK & AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
        shell: bash

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build AAB
        run: flutter build appbundle

      - name: Create GitHub Release & Upload Files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "🚀 New Flutter app release: `${{ github.ref_name }}`"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
